name: Generate GitHub Metrics

on:
  schedule: 
    - cron: "0 0 * * *"  # runs once daily at midnight UTC
  workflow_dispatch:  # allows manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AparnaKrishnakumar
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex
          plugin_languages_details: bytes-size, percentage
          plugin_isocalendar: yes
          plugin_repositories: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          plugin_lines: yes
          plugin_followup: yes
          plugin_stargazers: yes
          plugin_habits: yes
          plugin_habits_from: 200
